/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.apuntesdejava.virtualclassroom.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CourseSession service. Represents a row in the &quot;vc_CourseSession&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.apuntesdejava.virtualclassroom.model.impl.CourseSessionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.apuntesdejava.virtualclassroom.model.impl.CourseSessionImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CourseSession
 * @generated
 */
@ProviderType
public interface CourseSessionModel
	extends BaseModel<CourseSession>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a course session model instance should use the {@link CourseSession} interface instead.
	 */

	/**
	 * Returns the primary key of this course session.
	 *
	 * @return the primary key of this course session
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this course session.
	 *
	 * @param primaryKey the primary key of this course session
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the course session ID of this course session.
	 *
	 * @return the course session ID of this course session
	 */
	public long getCourseSessionId();

	/**
	 * Sets the course session ID of this course session.
	 *
	 * @param courseSessionId the course session ID of this course session
	 */
	public void setCourseSessionId(long courseSessionId);

	/**
	 * Returns the group ID of this course session.
	 *
	 * @return the group ID of this course session
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this course session.
	 *
	 * @param groupId the group ID of this course session
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this course session.
	 *
	 * @return the company ID of this course session
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this course session.
	 *
	 * @param companyId the company ID of this course session
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this course session.
	 *
	 * @return the user ID of this course session
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this course session.
	 *
	 * @param userId the user ID of this course session
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this course session.
	 *
	 * @return the user uuid of this course session
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this course session.
	 *
	 * @param userUuid the user uuid of this course session
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this course session.
	 *
	 * @return the user name of this course session
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this course session.
	 *
	 * @param userName the user name of this course session
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this course session.
	 *
	 * @return the create date of this course session
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this course session.
	 *
	 * @param createDate the create date of this course session
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this course session.
	 *
	 * @return the modified date of this course session
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this course session.
	 *
	 * @param modifiedDate the modified date of this course session
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the title of this course session.
	 *
	 * @return the title of this course session
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this course session.
	 *
	 * @param title the title of this course session
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this course session.
	 *
	 * @return the description of this course session
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this course session.
	 *
	 * @param description the description of this course session
	 */
	public void setDescription(String description);

	/**
	 * Returns the due date of this course session.
	 *
	 * @return the due date of this course session
	 */
	public Date getDueDate();

	/**
	 * Sets the due date of this course session.
	 *
	 * @param dueDate the due date of this course session
	 */
	public void setDueDate(Date dueDate);

	/**
	 * Returns the course ID of this course session.
	 *
	 * @return the course ID of this course session
	 */
	public long getCourseId();

	/**
	 * Sets the course ID of this course session.
	 *
	 * @param courseId the course ID of this course session
	 */
	public void setCourseId(long courseId);

}